# Generated by Django 4.1.3 on 2022-11-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=30)),
                ('esal', models.FloatField()),
                ('city', models.CharField(max_length=30)),
                ('contact_no', models.IntegerField()),
            ],
        ),
    ]
